### ISSUE TITLE
Add date to front matter

### ISSUE THREAD

**Issue by redfox58** [Rarst/wprss2hugo#2]
Please add date or publisedate or last update to front matter

**Comment by Rarst** [comment]
It should be there:

https://github.com/Rarst/wprss2hugo/blob/master/src/Handler/Post.php#L49

Could you be more specific where do you expect it that it's not present?

**Comment by redfox58** [comment]
yes  Sorry. I'm not careful .. I want to ask how to display the date in frontmatter? Because the export results don't have a date

**Comment by redfox58** [comment]
---
date: 2017-09-26T06:00:00+06:00
lastmod: 2017-10-11T17:30:00+06:00
....
...
...

---
my hope is a frontmatter like the one above

**Comment by Rarst** [comment]
As above `publishDate` is there and should work the same if `date` is not present (it's closer in meaning to WP post date).

I don't remember why I am not adding `lastmod` from post date modified, but on WP side that field can be a mess in what it means.

What is actual _problem_ you are having?

**Comment by redfox58** [comment]
I have file xml but after convert with this script date is not show in front matter...

(I just want to sho date to my frontmatter)
This is front matter after convert
---
title: 'Bitcoin Price Usd 2 Years Ago'
authors:
    - Admin
id: 86
url: /bitcoin-price-usd-2-years-ago/
'':
    - ''
categories:
    - wallpaper
tag:
    - price
    - years

**Comment by Rarst** [comment]
What does this post look like in the XML file?

**Comment by redfox58** [comment]
This is my file xml
https://github.com/redfox58/recipe-book/blob/master/wp2.xml

And this 

Output
https://github.com/redfox58/recipe-book/blob/master/asset-gates-bitcoin.md

**Comment by Rarst** [comment]
The date format in your XML doesn't look right to me:

```xml
<wp:post_date><![CDATA[2021-06-28T16:33:49Z]]></wp:post_date>
```

This is what the format should normally be:

```xml
<wp:post_date><![CDATA[2019-04-01 18:00:31]]></wp:post_date>
```

Not sure why would it be that way, but it's not what my code expects.

Are you exporting from a normal up-to-date WordPress install?

**Comment by redfox58** [comment]
Yes.. fix 
.. i modifed your handler and fix
